run name *args:
    sudo ./bin/{{ name }} {{ args }}

build-dir name:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p build/{{ name }} bin
    objs=()
    for src in src/userspace/{{ name }}/*.c; do
        obj=build/{{ name }}/$(basename "$src" .c).o
        objs+=("$obj")
        clang -O2 -g -Wall -c "$src" -o "$obj"
    done
    clang "${objs[@]}" -o bin/{{ name }} -lxdp -lbpf

build name:
    @just _build src/userspace/{{ name }}.c build/{{ name }}.o
    @just _bin build/{{ name }}.o bin/{{ name }}

run-xdp name:
    @just build-xdp {{ name }}
    @just load-xdp {{ name }}

build-xdp name:
    @just _build-xdp src/ebpf/{{ name }}.c build/{{ name }}.o

load-xdp name ifname:
    @just _load-xdp build/{{ name }}.o {{ ifname }} -m skb

status:
    sudo xdp-loader status

unload ifname:
    sudo xdp-loader unload {{ ifname }} --all

prog-list:
    sudo bpftool prog list

####

_build source output:
    clang -O2 -g -Wall -c {{ source }} -o {{ output }}

_bin source output:
    clang {{ source }} -o {{ output }} -lxdp -lbpf


_build-xdp source output:
    clang -O2 -g -Wall -target bpf -I/usr/include/aarch64-linux-gnu -c {{ source }} -o {{ output }}

_load-xdp path ifname:
    sudo xdp-loader load {{ ifname }} {{ path }} -m skb
