i_flag := "-I/usr/include/" + arch() + "-linux-gnu"

## USERSPACE

run name *args:
    sudo ./bin/{{ name }}/bin {{ args }}

build name:
    @mkdir -p build bin
    @just build-raw src/userspace/{{ name }}.c build/{{ name }}.o
    @just _bin build/{{ name }}.o bin/{{ name }}

build-dir name:
    #!/usr/bin/env bash
    set -euo pipefail

    mkdir -p build/{{ name }} bin
    objs=()

    for src in src/userspace/{{ name }}/*.c; do
        obj=build/{{ name }}/$(basename "$src" .c).o
        objs+=("$obj")
        clang -O2 -g -Wall -c "$src" -o "$obj"
    done

    mkdir -p bin/{{ name }}
    clang "${objs[@]}" -o bin/{{ name }}/bin -lxdp -lbpf

## XDP

run-xdp name:
    @just build-xdp {{ name }}
    @just load-xdp {{ name }}

build-xdp name:
    @mkdir -p build
    @just build-xdp-raw src/ebpf/{{ name }}.c build/{{ name }}.o

build-dir-xdp name:
    @mkdir -p build
    @just build-xdp-raw src/ebpf/{{ name }}/main.bpf.c build/{{ name }}.o

load-xdp name ifname:
    @just load-xdp-raw {{ ifname }} build/{{ name }}.o

## UTILITIES

status:
    sudo xdp-loader status

unload ifname:
    sudo xdp-loader unload {{ ifname }} --all

prog-list:
    sudo bpftool prog list

##

build-raw source output:
    clang -O2 -g -Wall -c {{ source }} -o {{ output }}

_bin source output:
    clang {{ source }} -o {{ output }} -lxdp -lbpf

build-xdp-raw source output:
    clang -O2 -g -Wall -target bpf {{ i_flag }} -c {{ source }} -o {{ output }}

load-xdp-raw ifname path *args:
    sudo xdp-loader load {{ ifname }} {{ path }} -m skb {{ args }}
